name: Bioconductor Package Gatekeeper

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      force_check:
        description: 'Force check all packages regardless of changes'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  actions: read

jobs:
  monitor-packages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        monitor-packages:
          runs-on: ubuntu-latest
    
          steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              fetch-depth: 0

          - name: Install rclone for deployment
            run: |
              sudo apt-get update
              sudo apt-get install -y curl
              curl https://rclone.org/install.sh | sudo bash

          - name: Get Bioconductor version from config.yaml
            id: get_bioc_version
            run: |
              bioc_version=$(grep '^  version:' config.yaml | head -1 | awk '{print $2}' | tr -d '"')
              echo "bioc_version=$bioc_version" >> $GITHUB_OUTPUT

          - name: Run gatekeeper steps in Bioconductor Docker
            uses: addnab/docker-run-action@v3
            with:
              image: bioconductor/bioconductor_docker:RELEASE_${{ steps.get_bioc_version.outputs.bioc_version//./_ }}
              options: |
                -v ${{ github.workspace }}:/workspace
                -w /workspace
              run: |
                mkdir -p package-status logs temp
                Rscript scripts/monitor-packages.R
                if [ -f "${GITHUB_OUTPUT}" ]; then
                  packages_to_check=$(grep '^packages_to_check=' "${GITHUB_OUTPUT}" | cut -d'=' -f2)
                else
                  packages_to_check=""
                fi
                if [ "$packages_to_check" != "" ]; then
                  Rscript scripts/check-packages.R "$packages_to_check"
                fi
                Rscript scripts/update-status.R
                Rscript scripts/generate-markdown-dashboard.R
                if [ "$packages_to_check" != "" ]; then
                  Rscript scripts/deploy-packages.R
                fi
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                FORCE_CHECK: ${{ github.event.inputs.force_check || 'false' }}
                RCLONE_CONFIG_PRODUCTION_TYPE: ${{ secrets.RCLONE_CONFIG_PRODUCTION_TYPE }}
                RCLONE_CONFIG_PRODUCTION_ACCESS_KEY_ID: ${{ secrets.RCLONE_CONFIG_PRODUCTION_ACCESS_KEY_ID }}
                RCLONE_CONFIG_PRODUCTION_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_CONFIG_PRODUCTION_SECRET_ACCESS_KEY }}
                RCLONE_CONFIG_PRODUCTION_ENDPOINT: ${{ secrets.RCLONE_CONFIG_PRODUCTION_ENDPOINT }}
                RCLONE_CONFIG_PRODUCTION_REGION: ${{ secrets.RCLONE_CONFIG_PRODUCTION_REGION }}

          - name: Commit and push changes
            run: |
              git config --local user.email "action@github.com"
              git config --local user.name "GitHub Action"
              git add package-status/ logs/ gatekeeper-dashboard.md status.txt
              if ! git diff --staged --quiet; then
                git commit -m "Update package status and logs - $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
                git push
              else
                echo "No changes to commit"

          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            if: always()
            with:
              name: gatekeeper-logs
              path: |
                logs/
                temp/
              retention-days: 30
          git push
